<?php

use App\Http\Controllers\ApprovalController;
use App\Http\Controllers\AuditLogController;
use App\Http\Controllers\BackupController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\MasterDataController;
use App\Http\Controllers\ReportController;
use App\Http\Controllers\SettingsController;
use App\Http\Controllers\StudentSpreadsheetController;
use App\Http\Controllers\StudentStatementController;
use App\Http\Controllers\TransactionController;
use App\Http\Middleware\UsePersonalAdmin;
use Illuminate\Support\Facades\Route;

Route::get('/', fn () => redirect()->route('dashboard'));
Route::get('/login', fn () => to_route('dashboard'))->name('login');
Route::middleware(UsePersonalAdmin::class)->group(function () {
    Route::get('/dashboard', DashboardController::class)->name('dashboard');
    Route::prefix('master')->name('master.')->group(function () {
        Route::get('/tahun-pelajaran', [MasterDataController::class, 'tahun'])->name('tahun');
        Route::post('/tahun-pelajaran', [MasterDataController::class, 'storeTahun'])->name('tahun.store');
        Route::patch('/tahun-pelajaran/{tahun}/aktifkan', [MasterDataController::class, 'activateTahun'])->name('tahun.activate');
        Route::delete('/tahun-pelajaran/{tahun}', [MasterDataController::class, 'destroyTahun'])->name('tahun.destroy');
        Route::get('/kelas', [MasterDataController::class, 'kelas'])->name('kelas');
        Route::get('/kelas/create', [MasterDataController::class, 'kelasCreate'])->name('kelas.create');
        Route::post('/kelas', [MasterDataController::class, 'kelasStore'])->name('kelas.store');
        Route::get('/kelas/{kelas}/edit', [MasterDataController::class, 'kelasEdit'])->name('kelas.edit');
        Route::patch('/kelas/{kelas}', [MasterDataController::class, 'kelasUpdate'])->name('kelas.update');
        Route::delete('/kelas/{kelas}', [MasterDataController::class, 'kelasDestroy'])->name('kelas.destroy');
        Route::get('/siswa', [MasterDataController::class, 'siswa'])->name('siswa');
        Route::post('/siswa', [MasterDataController::class, 'siswaStore'])->name('siswa.store');
        Route::patch('/siswa/{siswa}', [MasterDataController::class, 'siswaUpdate'])->name('siswa.update');
        Route::delete('/siswa/{siswa}', [MasterDataController::class, 'siswaDestroy'])->name('siswa.destroy');
        Route::patch('/siswa/{siswa}/status', [MasterDataController::class, 'siswaStatus'])->middleware('admin.role')->name('siswa.status');
        Route::post('/siswa/pindah-kelas', [MasterDataController::class, 'siswaMove'])->middleware('admin.role')->name('siswa.move');
        Route::post('/siswa/import', [StudentSpreadsheetController::class, 'import'])->name('siswa.import');
        Route::get('/siswa/export', [StudentSpreadsheetController::class, 'export'])->name('siswa.export');
        Route::get('/siswa/template', [StudentSpreadsheetController::class, 'template'])->name('siswa.template');
    });
    Route::get('/master/siswa/{siswa}/buku', [StudentStatementController::class, 'show'])->name('students.statement');
    Route::get('/master/siswa/{siswa}/buku/cetak', [StudentStatementController::class, 'print'])->name('students.statement.print');
    Route::get('/transaksi/{transaksi}/bukti', [TransactionController::class, 'receipt'])->name('transactions.receipt');
    Route::get('/backup', [BackupController::class, 'index'])->middleware('admin.role')->name('backups.index');
    Route::post('/backup', [BackupController::class, 'store'])->middleware('admin.role')->name('backups.store');
    Route::get('/backup/{filename}', [BackupController::class, 'download'])->middleware('admin.role')->where('filename', 'tabungan-[A-Za-z0-9-]+\\.zip')->name('backups.download');
    Route::resource('transaksi', TransactionController::class)->only(['index', 'create', 'store'])->names('transactions');
    Route::post('/transaksi/{transaksi}/koreksi', [TransactionController::class, 'reverse'])->middleware('admin.role')->name('transactions.reverse');
    Route::get('/approval', [ApprovalController::class, 'index'])->middleware('admin.role')->name('approval.index');
    Route::patch('/approval/{approval}', [ApprovalController::class, 'update'])->middleware('admin.role')->name('approval.update');
    Route::get('/audit-log', [AuditLogController::class, 'index'])->middleware('admin.role')->name('audit.index');
    Route::get('/laporan', [ReportController::class, 'index'])->middleware('admin.role')->name('reports.index');
    Route::get('/laporan/export', [ReportController::class, 'export'])->middleware('admin.role')->name('reports.export');
    Route::get('/laporan/export-xlsx', [ReportController::class, 'exportXlsx'])->middleware('admin.role')->name('reports.export.xlsx');
    Route::get('/laporan/export-pdf', [ReportController::class, 'exportPdf'])->middleware('admin.role')->name('reports.export.pdf');
    Route::get('/laporan/cetak', [ReportController::class, 'print'])->middleware('admin.role')->name('reports.print');
    Route::get('/laporan/rekap', [ReportController::class, 'recap'])->middleware('admin.role')->name('reports.recap');
    Route::get('/laporan/rekap/cetak', [ReportController::class, 'recapPrint'])->middleware('admin.role')->name('reports.recap.print');
    Route::get('/laporan/rekap/export-xlsx', [ReportController::class, 'recapXlsx'])->middleware('admin.role')->name('reports.recap.xlsx');
    Route::get('/pengaturan', [SettingsController::class, 'index'])->middleware('admin.role')->name('settings.index');
    Route::patch('/pengaturan', [SettingsController::class, 'update'])->middleware('admin.role')->name('settings.update');
});
