<script setup lang="ts">
import {Head,Link} from '@inertiajs/vue3';
import MainLayout from '../../Layouts/MainLayout.vue';
import Pagination from '../../Components/Pagination.vue';
defineProps<{student:any;summary:{masuk:number;keluar:number;saldo:number};items:any;pendingCount:number}>();
const rp = (value:number) => Number(value ?? 0).toLocaleString('id-ID');
</script>
<template><MainLayout><Head :title="'Buku tabungan · '+student.nama"/><main class="p-4 sm:p-6 lg:p-8"><div class="mx-auto max-w-7xl space-y-6">
    <Link href="/master/siswa" class="text-sm font-semibold text-indigo-600">← Daftar siswa</Link>
    <div class="flex flex-wrap items-end justify-between gap-4"><div><p class="clay-eyebrow">Buku tabungan siswa</p><h1 class="mt-2 text-2xl font-bold">{{student.nama}}</h1><p class="mt-2 text-sm text-slate-500">NIS {{student.nis}} · {{student.kelas?.nama_kelas ?? 'Tanpa kelas'}} · {{student.kelas?.tahun_pelajaran?.tahun ?? '—'}}</p><p v-if="student.kontak" class="mt-1 text-sm text-slate-500">Kontak: {{student.kontak}}</p></div><a :href="`/master/siswa/${student.id}/buku/cetak`" target="_blank" rel="noopener" class="sneat-primary rounded-lg px-4 py-3 text-sm font-semibold text-white">Cetak buku tabungan ↗</a></div>
    <div class="grid gap-4 sm:grid-cols-3"><div class="sneat-card p-6"><p class="text-sm text-slate-500">Saldo saat ini</p><p class="mt-2 text-2xl font-bold text-indigo-600">Rp {{rp(summary.saldo)}}</p></div><div class="sneat-card p-6"><p class="text-sm text-slate-500">Total setoran</p><p class="mt-2 text-2xl font-bold text-emerald-700">Rp {{rp(summary.masuk)}}</p></div><div class="sneat-card p-6"><p class="text-sm text-slate-500">Total penarikan</p><p class="mt-2 text-2xl font-bold text-rose-700">Rp {{rp(summary.keluar)}}</p></div></div>
    <p v-if="pendingCount" class="rounded-lg bg-amber-50 p-4 text-sm text-amber-800">Ada {{pendingCount}} pengajuan penarikan yang menunggu persetujuan. Saldo belum dikurangi. <Link href="/approval" class="font-bold underline">Lihat approval</Link></p>
    <section class="sneat-card overflow-hidden"><div class="border-b p-5"><h2 class="font-bold">Seluruh riwayat tabungan</h2><p class="mt-1 text-xs text-slate-500">Transaksi terakhir dicatat tampil paling atas. Buku cetak diurutkan berdasarkan tanggal transaksi.</p></div><div class="overflow-x-auto"><table class="sneat-table w-full text-left text-sm"><thead class="text-xs uppercase"><tr><th class="p-4">Tanggal</th><th class="p-4">Jenis</th><th class="p-4 text-right">Jumlah</th><th class="p-4">Keterangan</th><th class="p-4">Bukti</th></tr></thead><tbody class="divide-y"><tr v-for="item in items.data" :key="item.id"><td class="whitespace-nowrap p-4">{{item.tanggal}}</td><td class="p-4">{{item.jenis==='masuk'?'Setoran':'Penarikan'}}</td><td class="whitespace-nowrap p-4 text-right font-semibold" :class="item.jenis==='masuk'?'text-emerald-700':'text-rose-700'">Rp {{rp(item.jumlah)}}</td><td class="p-4">{{item.keterangan||'—'}}</td><td class="p-4"><a :href="`/transaksi/${item.id}/bukti`" target="_blank" rel="noopener" class="font-semibold text-indigo-600">Cetak ↗</a></td></tr><tr v-if="!items.data.length"><td colspan="5" class="p-10 text-center text-slate-500">Belum ada transaksi untuk siswa ini.</td></tr></tbody></table></div><Pagination :data="items"/></section>
</div></main></MainLayout></template>
